### ISSUE TITLE
Find out is cbdbd process running fine?

### ISSUE THREAD

**Issue by yogeshprasad** [punith-cloudbyte/touchstone#2]
Provide the proper error message if a process is not running properly.
A way to find out if a process is running fine or not.

**Comment by AmitKumarDas** [comment]
Let's raise issues in a way they can be understood by people who do not understand CloudByte.

**Comment by yogeshprasad** [comment]
Sure Amit.

Regards,
Yogesh
_CloudByte Inc._ http://www.cloudbyte.com/
